### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by geoperez** [unosquare/swan#137]
**Describe the bug**
I have a project in which I want to transfer a lot of data via web service.
 In one example, I have 12 megabytes of EPG data. 
The transmission takes about 90 seconds due to the serialization by the standard Json Serializer. 
When using NewtonSoft only about 3 seconds.

Comparison programm see attachment - it is a pure Console app.
[FastJsonTest.zip](https://github.com/unosquare/embedio/files/2207485/FastJsonTest.zip)

Of course I can handle the problem by using NewtonSoft, but I think the hint could be useful for the overall performance of the system. I'm not sure where else this Json component is used.

Original ticket: https://github.com/unosquare/embedio/issues/177 by @detlefm

**Comment by geoperez** [comment]
Current values:

..........
Min: 6.269 Max: 825.2277 Average: 20.155926
..........
Min: 2.521 Max: 12.5771 Average: 3.74317

**Comment by geoperez** [comment]
..........
Min: 8.6017 Max: 264.3828 Average: 15.967253
..........
Min: 4.1334 Max: 29.488 Average: 6.84043

**Comment by detlefm** [comment]
Hi,
thanks for the info.
I tried a new test program (see attachment) with the newest
version.(0.33.0.0).

Here are my numbers (only for Serialize, Deserialize is also possible but
not tested).
 /*
* Results:
* LoopCount 100000, ListSize 10
Serialize: Swan Min: 0 Max: 33,9158 Average: 0,32338533099999
Serialize: Newton Min: 0 Max: 110,7307 Average: 0,0331512859999997
Serialize: Fast Min: 0 Max: 15,9558 Average: 0,0261102879999998
LoopCount 10000, ListSize 100
Serialize: Swan Min: 2,9917 Max: 18,9398 Average: 4,51920777000003
Serialize: Newton Min: 0 Max: 1,1022 Average: 0,292315319999997
Serialize: Fast Min: 0 Max: 1,0402 Average: 0,224298279999999
LoopCount 1000, ListSize 1000
Serialize: Swan Min: 171,5187 Max: 239,3617 Average: 182,6435403
Serialize: Newton Min: 1,969 Max: 7,979 Average: 3,28920139999999
Serialize: Fast Min: 1,9681 Max: 5,9932 Average: 2,62697169999999
done
*/

I have always kept the number of loops and the number of listsize equal.
So the bigger the list the smaller the number of loops.
The larger the list, the more problematic the performance of Swan.and
(without the source code in detail to understand)
I think it is because with each element of a list, the structure of the
tree of the object is calculated again..
If the ProperyInfo tree is held in a cache (perhaps also beyond the call)
then the performance would have to improve significantly,
especially for a list with same elements.


Best regards.




2018-07-24 18:33 GMT+02:00 Geovanni Perez <notifications@github.com>:

**Comment by geoperez** [comment]
We have a `ProperyInfoCache`, but I'm still checking what is happening there. Thank you.

**Comment by geoperez** [comment]
Hi @detlefm, I just published a new prerelease version (https://www.nuget.org/packages/Unosquare.Swan.Lite/0.33.1-pre) using this branch, can you test it?

Thank you

**Comment by detlefm** [comment]
Ok, the numbers with this version are better but the main problem
(increasing time by large lists) remains.

I have done my own research based on the last public source code and I
found the reason ( I think).
In the  constructor of the Serializer you have this:

        //// Handle circular references correctly and avoid them
                if (options.ParentReferences.Any(p =>
ReferenceEquals(p.Target, obj)))
                {
                    _result = $"{{ \"$circref\":
\"{Escape(obj.GetHashCode().ToStringInvariant())}\" }}";
                    return;
                }


                options.ParentReferences.Add(new WeakReference(obj));

And this constructor is called for every item of the list.
Because of the static behavior of the object "options" ParentReferences
grow up to List Size. and the call "if (options.ParentReferences.Any())"
eats the time.

I havn't look for a solution but when I comment out this lines the timing
is stable and don't increase with list size.

I have seen some more possible improvements like getting the DateTime
Format for every item, the comma symbol
for every item but this are minor improvements.

Best regards.


2018-07-25 20:43 GMT+02:00 Geovanni Perez <notifications@github.com>:

**Comment by detlefm** [comment]
Hi,
I had changed the source from  List<WeakReference>  to HashSet<object> and
it works fine and fast.
I am not a C# guru so I am not really sure that this is the same - but I
guess for this purposes it must work.
You will find an object which is already converted and put the HashCode to
the string representation,

I am also not sure if a Json Parser can do a lot with this information
because the Hashcode is never used before.
When I think at a short list like :
class AClass{
     int content;
     AClass next;
}
and the objects  A(content=0, next = B), B(content=1, next = A),
C(content=2, next = B)

For a parser it is not visibile that the reference from Object C refs zu
Object B and not to Object A

But whatever I think a HashSet will work.

Best regards.

2018-07-25 20:43 GMT+02:00 Geovanni Perez <notifications@github.com>:

**Comment by detlefm** [comment]
Really?
The object can't be removed during the run of the Serializer becaused it is
referenced from the object you currently serialize.
Or do I miss something?
When we look at all possibilities then to make a snapshot (as json string)
of an object,  the object must be locked to be sure that no other thread is
changing the object.
or might it possible to make a snapshot of a not stable object?

If you have a really big object (with a lot of references, a list or tree
or whatever) the actual implementation eats the time at this point.
And it eats it even if no references exists. So you can decide which
problem is bigger:
The problem you might have that the GC can't work for a short time or the
problem you have with a long running Serialization.

The way around maybe to parse first and assume there are no references
(what is the case for most of the web scenarios) and only when you find the
possibility of circular
references you do it with the Weakreference. In this case for the first run
you look only for classes and not for objects.

Best regards



2018-07-27 17:26 GMT+02:00 Geovanni Perez <notifications@github.com>:

**Comment by geoperez** [comment]
If you are working in a multithreading application, one thread may be serializing the application state, meanwhile another thread disposing one object from the same state.

**Comment by detlefm** [comment]
Yes - I understand - but do you really want to allow this?
 " meanwhile another thread disposing one object from the same state." ->
thats sounds for me like big dark hole of an unstable  state.

The resulting string representation rellects not (or seldom) a valid
status.because the GC operations are not atomic in the meaning of
application transactions.

And thats (to be sure) "normally" must result in something like:

public string Serialize(object obj){
lock (obj){
     return do_the_serialization(obj);
}
}

But thats your responsibility - I hope you find a way to improve the speed
and reach your goals.

Best regards.

2018-07-27 17:55 GMT+02:00 Geovanni Perez <notifications@github.com>:

**Comment by geoperez** [comment]
I included your suggestion to use `HashSet<object>`, I left the `List<WeakReference>` but only when the developer set an initial value.

Let me know if you see a better performance using this nuget version [0.33.2-pre](https://www.nuget.org/packages/Unosquare.Swan.Lite/0.33.2-pre)

**Comment by detlefm** [comment]
Hi,
the problem remains but on a very lower level (increasing time consumption
per item when list grows)
MiniTestClass is a class with only one member.
With the newest (pre) version the time consumption (per item)  increases
from 0.0022 to 0.0031.
That is a big step forward comparing the old version whre the time
consumption increases from   0,0075 to  2,3870236695

Without your changes only changes I made on top of the public version I get
with WeakReferences better results.
The numbers increases from   0,008 List of 10)  to    0,0092 (List of
100000).
I change from:
List<WeakReference>
to
public Dictionary<int, List<WeakReference>> ParentReferences { get; set; }
= new Dictionary<int, List<WeakReference>>();

and in the query I change the code to:

   int hashCode = obj.GetHashCode();

                if (options.ParentReferences.TryGetValue(hashCode, out
List<WeakReference> result)) {
                    if (result.Any(p => ReferenceEquals(p.Target, obj))) {
                        _result = $"{{ \"$circref\":
\"{Escape(obj.GetHashCode().ToStringInvariant())}\" }}";
                        return;
                    }
                } else {
                    options.ParentReferences[hashCode] = new
List<WeakReference>();
                }


                options.ParentReferences[hashCode].Add(new
WeakReference(obj));


that results in a list of Hashcode (there are not really unique but ...) so
the query result.Any()
runs only against a very small list.
Another possibility is to use a SortedList with a BinarySearch.

Best regards



Output of timing - Source code of test program hasn't changed.


Pre version 0.33.2pre

MiniTestClass
LoopCount 100000, ListSize 10
Serialize: Swan Min: 0 Max: 42,8851 Average: 0,022341576 Per Item:
0,0022341576
Serialize: Newton Min: 0 Max: 108,6897 Average: 0,00719020299999999 Per
Item: 0,000719020299999998
LoopCount 10000, ListSize 100
Serialize: Swan Min: 0 Max: 1,0838 Average: 0,198269520000001 Per Item:
0,00198269520000001
Serialize: Newton Min: 0 Max: 1,031 Average: 0,04757092 Per Item:
0,0004757092
LoopCount 1000, ListSize 1000
Serialize: Swan Min: 0,9744 Max: 3,9671 Average: 1,9497853 Per Item:
0,0019497853
Serialize: Newton Min: 0 Max: 1,0261 Average: 0,452822299999999 Per Item:
0,000452822299999999
LoopCount 100, ListSize 10000
Serialize: Swan Min: 23,9144 Max: 34,8842 Average: 28,174667 Per Item:
0,0028174667
Serialize: Newton Min: 3,9307 Max: 7,9498 Average: 4,697665 Per Item:
0,0004697665
LoopCount 10, ListSize 100000
Serialize: Swan Min: 296,2078 Max: 334,1037 Average: 318,44711 Per Item:
0,0031844711
Serialize: Newton Min: 46,8699 Max: 67,8415 Average: 51,76114 Per Item:
0,0005176114
done



Last version 0.33

MiniTestClass
LoopCount 100000, ListSize 10
Serialize: Swan Min: 0 Max: 33,9092 Average: 0,0752379829999995 Per Item:
0,00752379829999995
Serialize: Newton Min: 0 Max: 108,708 Average: 0,00703128499999998 Per
Item: 0,000703128499999998
LoopCount 10000, ListSize 100
Serialize: Swan Min: 0 Max: 3,0005 Average: 0,868875209999996 Per Item:
0,00868875209999996
Serialize: Newton Min: 0 Max: 1,0901 Average: 0,0467750399999999 Per Item:
0,0004677504
LoopCount 1000, ListSize 1000
Serialize: Swan Min: 28,9223 Max: 60,8366 Average: 32,7698114 Per Item:
0,0327698114
Serialize: Newton Min: 0 Max: 1,9981 Average: 0,4886928 Per Item:
0,0004886928
LoopCount 100, ListSize 10000
Serialize: Swan Min: 2407,5825 Max: 2747,429 Average: 2515,877596 Per Item:
0,2515877596
Serialize: Newton Min: 2,9921 Max: 8,948 Average: 4,837978 Per Item:
0,0004837978
LoopCount 10, ListSize 100000
Serialize: Swan Min: 225922,8605 Max: 249758,6879 Average: 238702,36695 Per
Item: 2,3870236695
Serialize: Newton Min: 45,8846 Max: 55,8329 Average: 49,88152 Per Item:
0,0004988152
done


My version
MiniTestClass
LoopCount 100000, ListSize 10
Serialize: Swan Min: 0 Max: 33,8927 Average: 0,0851882520000005 Per Item:
0,00851882520000005
Serialize: Newton Min: 0 Max: 112,6881 Average: 0,00694229899999999 Per
Item: 0,000694229899999999
LoopCount 10000, ListSize 100
Serialize: Swan Min: 0 Max: 6,9808 Average: 0,725558099999993 Per Item:
0,00725558099999993
Serialize: Newton Min: 0 Max: 1,0243 Average: 0,0458786000000001 Per Item:
0,000458786000000001
LoopCount 1000, ListSize 1000
Serialize: Swan Min: 4,9863 Max: 10,9695 Average: 7,29451349999999 Per
Item: 0,00729451349999999
Serialize: Newton Min: 0 Max: 1,0243 Average: 0,4427955 Per Item:
0,0004427955
LoopCount 100, ListSize 10000
Serialize: Swan Min: 76,7955 Max: 93,772 Average: 84,922911 Per Item:
0,0084922911
Serialize: Newton Min: 3,959 Max: 8,9753 Average: 4,538134 Per Item:
0,0004538134
LoopCount 10, ListSize 100000
Serialize: Swan Min: 912,5379 Max: 972,4217 Average: 929,71161 Per Item:
0,0092971161
Serialize: Newton Min: 44,8805 Max: 75,7991 Average: 51,46241 Per Item:
0,0005146241
done




2018-07-27 19:33 GMT+02:00 Geovanni Perez <notifications@github.com>:

**Comment by geoperez** [comment]
Hi @detlefm,

I created a new nuget with the Dicitonary, can you benckmark it?

https://www.nuget.org/packages/Unosquare.Swan.Lite/0.33.3-pre

**Comment by detlefm** [comment]
Hi,
yes - the results are good.

Swan is comparing to Newton 10 times slower but stable in timing when the
list grows.

The time consumption grows from 0.004 per item (List of 10) to 0.005  per
item (List of 100000).

My first suggestions using a HashSet might be a little faster but I think
not significant.

Best regards,


MiniTestClass
LoopCount 100000, ListSize 10
Serialize: Swan Min: 0 Max: 40,8902 Average: 0,0372302179999994 Per Item:
0,00372302179999994
Serialize: Newton Min: 0 Max: 117,6853 Average: 0,007269694 Per Item:
0,0007269694
LoopCount 10000, ListSize 100
Serialize: Swan Min: 0 Max: 2,9924 Average: 0,327424629999996 Per Item:
0,00327424629999996
Serialize: Newton Min: 0 Max: 1,0255 Average: 0,04727371 Per Item:
0,0004727371
LoopCount 1000, ListSize 1000
Serialize: Swan Min: 1,9717 Max: 7,9795 Average: 3,22038699999999 Per Item:
0,00322038699999999
Serialize: Newton Min: 0 Max: 1,9954 Average: 0,4488075 Per Item:
0,0004488075
LoopCount 100, ListSize 10000
Serialize: Swan Min: 36,9009 Max: 65,8241 Average: 44,670526 Per Item:
0,0044670526
Serialize: Newton Min: 3,9659 Max: 9,9732 Average: 4,777217 Per Item:
0,0004777217
LoopCount 10, ListSize 100000
Serialize: Swan Min: 473,7321 Max: 507,6424 Average: 494,57713 Per Item:
0,0049457713
Serialize: Newton Min: 45,8768 Max: 81,7809 Average: 55,05278 Per Item:
0,0005505278
done


2018-07-30 16:59 GMT+02:00 Geovanni Perez <notifications@github.com>:
