### ISSUE TITLE
Terminal ReadPrompt output

### ISSUE THREAD

**Issue by k3z0** [unosquare/swan#150]
**Describe the bug**
Terminal class "ReadPrompt" extension method is not showing the options properly. In the following image you can see that options A and B do not appear.

![imagen](https://user-images.githubusercontent.com/5455304/44801368-7f9c9f80-ab7e-11e8-8ee3-3237b5b35aba.png)

**Comment by geoperez** [comment]
Checking the source code where is happening, my guess the issue comes from the RaspberryIO method `NetworkSettings.Instance.RetrieveWirelessNetworks`. I remember that method was buggy in early versions, and @k3z0 is using a really old version.

Try to send a random number of options between 10 and 20. If you can't reproduce please close this issue. We will address the issue in the internal project.

**Comment by geoperez** [comment]
Status?
