### ISSUE TITLE
Breaking Changes / Release Note

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/swan#158]
Hi,

I just spend sometime tracking down a regression in my app. After 30min, i found that the problem came from Swan.Lite v0.34.0 (OK) but v0.34.2 (buggy).

I just the swan terminal logging system to save "Debug - Start of Request" (embedio) in a log file in production.

v0.34.2 introduced a new var `GlobalLoggingMessageType` and change the way messageType are filtered by default : 

```C#
                 if (IsDebuggerAttached)
                {
                    DisplayLoggingMessageType =
                        LogMessageType.Debug |
                        LogMessageType.Error |
                        LogMessageType.Info |
                        LogMessageType.Trace |
                        LogMessageType.Warning |
                        LogMessageType.Fatal;
                }
                else
                {
                    DisplayLoggingMessageType =
                        LogMessageType.Error |
                        LogMessageType.Info |
                        LogMessageType.Warning |
                        LogMessageType.Fatal;
                }

GlobalLoggingMessageType = DisplayLoggingMessageType;
```

I've added `GlobalLoggingMessageType` to my app with correct MessageType, so no problem.

But, how do handle these change ? Do you use SemVer ?

Thanks for your answer and Swan rockssss

**Comment by geoperez** [comment]
My bad, I didn't see any side effect when a add the new global setting. 

We try to use SemVer and a small release notes in the [nuget information](https://www.nuget.org/packages/Unosquare.Swan.Lite) and sometimes in the Release tab here in [Github](https://github.com/unosquare/swan/releases), but since we consider SWAN as beta, we try to enforce SemVer in libraries starting from version 1.0.

Sorry for the inconvenience. And thanks for the heads up!

My guess I can close this issue?

**Comment by bufferUnderrun** [comment]
No problem, it was just a question. You're doing a great job with theses lib (swan&embedio).

You can close the issue.
