### ISSUE TITLE
Terminal Logging does not flush

### ISSUE THREAD

**Issue by mariodivece** [unosquare/swan#221]
Saple Code:
```csharp
    using Swan;
    using Swan.Logging;
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    class Program
    {
        static void Main(string[] args)
        {
            "Program finished.".Info();
            Terminal.Flush();
        }
    }
```

Message never gets displayed.

Additionally I see certain bad practices on message queuing (messages sometimes not diplayed in the order they were sent)

Unsure if the exclusive timer is the right tool for outputting messages. Come discuss with me.

**Comment by k3z0** [comment]
Hi @mariodivece 

This behavior is because of the async nature of the logger. When you invoke any logger extension method, like `.info() `, the logger class [schedules a Task](https://github.com/unosquare/swan/blob/c4684ebb4867bbe40bb3f52c09ea0a33cadcb5c5/src/Swan.Lite/Logging/Logger.cs#L656) (for any registered logger) that, when executed, logs the message to the final destination. In this case, the logger sends the message to the terminal that, in turn, enqueues the message for later display.

Because the tasks are enqueued to run on the ThreadPool, we have no control in the order in which the tasks are actually executed, that's why messages are not always displayed in the order they were sent and that's why when you call `Terminal.Flush()` the Terminal message queue it's empty because the scheduled task hasn't been executed yet.

A workaround could be using a thread sleep before flushing to give it some time to the log task to be executed.

```csharp
static void Main(string[] args)
{
    "Program finished.".Info();
    Thread.Sleep(100);
    Terminal.Flush();
}
```

We are going to analyze if it would be the solution to add a certain amount of sleep time to the `Flush` function, nevertheless, even adding the sleep time we can't ensure there aren't more pending tasks.

**Comment by geoperez** [comment]
@rdeago I did some changes in the PR #224 using your suggestion of BlockingCollection.

I see good behavior when the Terminal is called directly with Write or WriteLine. But using logging methods, the output is unordered. And I feel this is a expected behavior because the logger should not block.

@k3z0 thoughts ?

**Comment by rdeago** [comment]
@geoperez forgive this old grumpy coder, but if there is one thing whose output absolutely, positively MUST be ordered, it's the log. An unordered log may easily trick you into thinking the flow of execution is different from what it really is, making debugging an exercise in frustration (as if it wasn't already).

The logger should not block _if possible_. `BlockingCollection.TryAdd` _can_ block, hopefully for a very short time, but this is the price you pay for correct serialization of log entries. I personally am fine with that; your mileage may of course vary, depending on your application's real-time requisites.

It seems to me that what you are really testing [here](https://github.com/unosquare/swan/pull/224/commits/2e0f8ae34a17b2c80cf0fbd183fbdf59cfc5d205#diff-cc6ff7b0831f61c1380411b40d4bf52dR23-R30) is the order in which `Parallel.ForEach` decides to execute your thousand instruction blocks. I may be wrong here, but maybe the results you are seeing depend on this.

Just out of curiosity, do you get the same results when logging to a file?

**Comment by k3z0** [comment]
@geoperez I think the problem of the logging is the [Task ](https://github.com/unosquare/swan/blob/0a435246ec53237a8fb2450718dfa2a450fe4f9a/src/Swan.Lite/Logging/Logger.cs#L656)the logger schedules for log each message. 

Maybe this process must be Sync in order to have the output ordered properly. @mariodivece had suggested to use a central message queue in the logger rather than use local queues in each _ILogger_ implementation.

**Comment by geoperez** [comment]
I remove the task from the logger. Now returning to the original issue. This will work just fine:

```
 public static async Task Main()
        {
            Terminal.WriteLine("Program finished.");
            Terminal.Flush();
        }
```

But using `Info` extension method will not because `Terminal.Flush` is not aware of Console Logger. I don't know if I need to connect both.

**Comment by rdeago** [comment]
@geoperez `TerminalLogger` should write through `Terminal` methods IMHO. Otherwise you're asking `Terminal.Flush` for nothing short of a miracle.

Let's recap:

* there is `Terminal`, used to interface with the console, and there is `Logger`, used to log messages;
* `Logger` can have one or more back-ends, one of which is `TerminalLogger`;
* two basic requirements for `Logger` are in apparent conflict:
  - messages must appear in the log in the same order in which they are generated (this _could_ be achieved by logging synchronously), and
  - logging a message must have the minimum possible impact on a thread's performance and determinism (this rules out synchronous logging);
* the best ~solution~ compromise seems to be as follows (@mariodivece and yours truly seem to have come to the same conclusion here):
  - when generating a log message, don't send it to back-ends at once - instead, add it to a (thread-safe) queue;
  - have a thread (not a `Task`, a plain old `Thread`) that dequeues log messages and sends them to back-ends;
* if you want to wait for all expected output to be sent to the console before exiting a program, the following steps seem compulsory to me:
  - have a mechanism to stop `Logger` from adding to the queue (in case there are some background threads still continuously sending messages) - this may be a simple `bool` (or `volatile bool`) field, set via a method, and checked before adding to the queue;
  - upon exiting the program, _first_ stop the logger, _then_ flush the queue, _then_ flush the terminal;
  - `TerminalLogger` must use `Terminal` instead of writing to the console directly.
